import type { Metadata } from 'next'
import './globals.css'
import { Auth0Provider } from '@auth0/nextjs-auth0'
import localFont from 'next/font/local'

const myFont = localFont({
  src: './fonts/ABCMonumentGrotesk.woff2',
})

export const metadata: Metadata = {
  title: 'Neoefivika',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} antialiased`}>
        <Auth0Provider>{children}</Auth0Provider>
      </body>
    </html>
  )
}
